package ai.nexa.core.data.conversation

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/** Persisted conversation metadata. IDs are generated by the caller and remain stable across sync. */
@Entity(tableName = "conversations")
data class ConversationEntity(
    @PrimaryKey val id: String,
    val title: String?,
    @ColumnInfo(name = "created_at_epoch_ms") val createdAtEpochMillis: Long,
    @ColumnInfo(name = "updated_at_epoch_ms") val updatedAtEpochMillis: Long,
) {
    init {
        require(id.isNotBlank()) { "Conversation id cannot be blank" }
        require(createdAtEpochMillis >= 0) { "Conversation creation time cannot be negative" }
        require(updatedAtEpochMillis >= createdAtEpochMillis) {
            "Conversation update time cannot precede creation"
        }
    }
}
